---
contact_info:
  label: Contact Info
  fields:
    phone_number:
      type: string
    formatted_address:
      type: string
    simple_address:
      type: string
    email_address:
      type: string
