# Human readable name of this type
name: Services
slug: services
description: Used to identify Featured and regular Services that Canvas Innovations offers
label_field_name: title

order_by: title

# Valid values: asc (ascending) and desc (descending). Set to asc by default.
# order_direction: asc

# Specify a field slug to group entries by that field in the back-office.
# group_by: <your field>

# Control the display of the content type in the back-office.
display_settings:
  seo: false              # display the SEO tab for the content entries
  advanced: false         # display the Advanced tab for the content entries
#   position: 1             # position in the sidebar menu
#   hidden: false           # hidden for authors?

# A list describing each field
fields:
- title: # The lowercase, underscored name of the field
    label: Title # Human readable name of the field
    type: string
    required: true
    hint: Explanatory text displayed in the back office
    localized: false

- featured:
    label: Featured?
    type: boolean

- featured_image: # The lowercase, underscored name of the field
    label: Featured image # Human readable name of the field
    type: file
    required: false
    hint: Explanatory text displayed in the back office
    localized: false

- brief: # The lowercase, underscored name of the field
    label: Brief # Human readable name of the field
    type: text
    required: false
    hint: A brief intro to this Offering Type
    localized: false
    # text_formatting: html # html (uses rich text editor), markdown or text (uses plain text editor)


- description: # The lowercase, underscored name of the field
    label: Description # Human readable name of the field
    type: text
    required: false
    hint: Explanatory text displayed in the back office
    localized: false
    # text_formatting: html # html (uses rich text editor), markdown or text (uses plain text editor)

- projects: # The lowercase, underscored name of the field
    label: Projects # Human readable name of the field
    type: many_to_many
    required: false
    hint: What projects included this Service
    localized: false    # Define the slug of the target content type (eg. comments)
    class_name: projects
    # Define the name of the field referring to Offering types in the target content type (eg. post)
    inverse_of: services
    # If you want to manage the entries of the relationship directly from the source entry
    ui_enabled: true

- images:
    label: Images
    type: has_many
    class_name: images
    inverse_of: service
